### ISSUE TITLE
Blueprint Badge Proposal

### ISSUE THREAD

**Issue by nacidai** [eclipse-sdv-blueprints/blueprints#14]
## Introduction:
Collaboration among Eclipse SDV projects is pivotal for the success and adoption for SDV technologies. To foster a culture of collaboration and recognize the efforts of SDV projects that actively engage in collaborative blueprints, we propose the creation of an "SDV Blueprint Badge." 

This badge will serve as a symbol of collaboration within the SDV community, inspiring and motivating projects to engage in mutually beneficial development and consolidation.  In additions these badges may help earn "maturity" credits for the SDV maturity initiative.

## Objective:
The primary objective of the SDV Blueprint Badge is to incentivize and recognize collaboration among SDV projects. By acknowledging and rewarding projects that actively participate in collaborative initiatives, the badge aims to foster a culture of cooperation, knowledge sharing, and innovation within the SDV ecosystem.

## Badge Criteria:
Establish clear criteria that projects must meet to qualify for the Blueprint Badge.  Examples of criteria may include:

## Key Collaboration Metrics:

- The participation and/or use of a technology from SDV or Eclipse project (maybe other OSS projects too) in a particular project earns the blueprint a unit of badge 
    - e.g: one SDV project used in a blueprint one badge(star) for the BP, - two SDV projects collaborating in a BP, two badges(stars) for the BP 
- Participating SDV project also earns a blueprint badge
    -  An SDV tech/project used in one blueprint, one BP badge, two blueprints two badges etc
- Cross-blueprint exchange and participation earns extra stars for BP project

## Recognition and Benefits:
A beautiful logo to display with pride :) at participating projects

**Comment by eriksven** [comment]
I like the overall idea. 
Thank you to @nacidai for writing the proposal! To have a BP badge is a good indication of how well-integrated a project and technology piece is in the overall ecosystem. A BP badge can thus be an additional motivation for such community work.

However, I would not base the levels of the badge on quantity metrics like the number of BPs in which the project is involved.  We are more interested that a project is an essential solution piece of the BP and that the developers did not only add it to increase the BP count. Therefore, I am more in favor of quality over quantity here. 
Do we actually need different tiers for a BP badge at the moment?

For now, I would also not hand out badges to the BPs to avoid confusion about the reasons for awarding the badge. For me, there is a difference between developing a technology in a project or creating a BP around projects. We could later think of a separate badge for BPs adopting Eclipse SDV projects. However, I am unsure whether this is necessary because the main goal for a BP is already to utilize and showcase Eclipse SDV and adjacent technologies.

When it comes to earning "maturity" credit, I am also not sure whether being part of BP is a good factor toward maturity metrics. Adoption might be an indicator of the maturity of the codebase.  However, being part of a BP does not necessarily say much about the community and the processes in the project itself (documentation, requirements tracing, CI/CD, etc.). In addition, we need to accept that being part of a BP does not directly imply that the projects are proven in production.

**Comment by nacidai** [comment]
Thank you for the feedback

> Therefore, I am more in favor of quality over quantity here. Do we actually need different tiers for a BP badge at the moment?

I think it depends; It is very hard to measure quality, and my  feeling is that a quality BP is also popular and attracts different technologies as a playground to showcase themselves (i.e. FMS). It i snot perfect, but I cannot think of many other metrics that would be able to measure this.  On the other hand I agree with you that ranking BPs is a clear indication of  having a showcase of a technology but not many other things. 

 
> When it comes to earning "maturity" credit, I am also not sure whether being part of BP is a good factor toward maturity metrics.

The maturity dimension was suggested by Dana Verde, and BPs are a part of their list of criteria but I am not clear myself how it relates to a maturity ranking.  It would be good to have their feedback here.

**Comment by nacidai** [comment]
During the regular BP monthly zoom call, it was decided to adopt a simple process for BP "badges":

In the sprit of acknowledging, incentivizing, and recognize collaboration among SDV projects an "SDV Blueprint Badge" will be  rewarded to the SDV projects that actively participate in one or more SDV blueprints.

A badge design will be provided by the eclipse foundation.

I will close this issue and add this simple badge description at github repo [BP Process](https://github.com/eclipse-sdv-blueprints/blueprints)

**Comment by nacidai** [comment]
[Badge Documentation](https://github.com/eclipse-sdv-blueprints/blueprints/blob/main/README.md#sdv-blueprints-badge)
